services:
    gunicorn:
        image: 884275084301.dkr.ecr.eu-west-3.amazonaws.com/mysocial_gunicorn:latest
        command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker --workers 1 --bind 0.0.0.0:5000 wsgi:app
        ports:
            - 5000:5000
        networks:
            - mysocial
    nginx:
        image: 884275084301.dkr.ecr.eu-west-3.amazonaws.com/mysocial_nginx:latest
        command: nginx -g "daemon off;"
        ports:
            - 80:80
        depends_on:
            - gunicorn
        networks:
            - mysocial

networks:
    mysocial: